name: TAC sanity checks and tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  common_checks:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install dependencies (ubuntu-latest)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install pipenv
          pip install tox
      - name: Code style check
        run: |
          tox -e black-check
          tox -e flake8
      - name: Static type check
        run: tox -e mypy

  integration_checks:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install dependencies (ubuntu-latest)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install pipenv
          pip install tox
          sudo apt-get install -y protobuf-compiler

      - name: Unit tests
        run: |
          tox -e py3.7 -- -m 'integration'

  platform_checks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - if: matrix.os == 'ubuntu-latest'
      name: Install dependencies (ubuntu-latest)
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get autoremove
        sudo apt-get autoclean
        pip install pipenv
        pip install tox
        sudo apt-get install -y protobuf-compiler
    # use sudo rm /var/lib/apt/lists/lock above in line above update if dependency install failures persist
    # use sudo apt-get dist-upgrade above in line below update if dependency install failures persist
    - if: matrix.os == 'macos-latest'
      name: Install dependencies (macos-latest)
      run: |
        pip install pipenv
        pip install tox
        brew install protobuf
    - if: matrix.os == 'windows-latest'
      name: Install dependencies (windows-latest)
      run: |
        pip install pipenv
        pip install tox
        echo "::add-path::C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64"
        choco install protoc
      # python scripts/update_symlinks_cross_platform.py
    - name: Unit tests
      run: |
        tox -e py${{ matrix.python-version }} -- -m 'not integration'
